#!/bin/bash

##########################################################3############################
#                                                                                     #
# ### Download da Lista de Dependências do Multilib para o Slackware - Versão 1.0 ### #
#                                                                                     #
# By Mauricio Ferrari                                                                 #
#                                                                                     #
# Compatibilidade YAD e ZENITY                                                        #
#                                                                                     #
#######################################################################################

DIAG=${DIAG:-"yad"}
TITLE="Baixar Lista de Dependências Multilib"
PARMS='--window-icon=wine.png --width=400'
PROGRESS="--progress --pulsate --no-cancel"

[ ! $(which "$DIAG" 2>&-) ] && DIAG="zenity"


# ### Função que mostra as barras de progresso ###

_progress()
{
	[ "$DIAG" == "yad" ] && {
		(while :; do x=$(( x + 1 )); echo $x; sleep 0.07; done | "$DIAG" --title="$TITLE" $PARMS $PROGRESS) &
	} || {
		(while :; do echo "#"; done | "$DIAG" --title="$TITLE" $PARMS $PROGRESS) &
	}
}


# ### Parâmetros para o YAD ###

[ "$DIAG" == "yad" ] && {
	PARMS="$PARMS --center"
	PROGRESS="$PROGRESS --no-buttons --hide-text"
}


# ### Coletando Informações da Página ###

_progress
wget -c http://www.slackware.com/~alien/multilib/$(cut -d" " -f2 /etc/slackware-version)/FILELIST.TXT
pkill "$DIAG"


# ### Finalizando ###

"$DIAG" --title="Concluído" --window-icon=wine.png \
	$( [ "$DIAG" == "yad" ] && echo "--center" || echo "--width=160" ) \
	--timeout=2 --info --text='Download Concluído!\n'
